### ISSUE TITLE
works fine with qemu, doesn't work on real boot

### ISSUE THREAD

**Issue by alexandregjr** [so-i-2019/boot-boota#2]
Works fine with qemu, but when i try to make it work on real boot, doesn't work.
Maybe its stuck because my computer has a UEFI Secure Boot. But even when i try to change from UEFI Secure Boot to Legacy Boot, boot gets stuck in a black screen with the cursor at the final line, near the middle of the screen.
Eduardo is trying to test on his computer, but we don't really know what is happening.

**Comment by monacofj** [comment]
Ok, working on it
